spring.application.name = firstapi

#spring.datasource.url = jdbc:h2:mem:namederdb
spring.datasource.url = jdbc:h2:file:~/firstapi
spring.datasource.username = tomasz
spring.datasource.password = geheim
spring.h2.console.enabled = true
#spring.h2.console.path = /h2-console

# Automatische Erzeugung von Tabellen
spring.jpa.hibernate.ddl-auto = update
